REM these are the arithmetic ops.
REM Note that no spaces are needed around the ops.
+-*/%()

REM relational ops.
<<=>>==<>

REM logical ops.
NOT AND OR

REM some special tokens.
,;

REM these are the commands
IF THEN ELSE ENDIF GOTO GOSUB RETURN FOR TO STEP NEXT
WHILE WEND DO UNTIL BREAK CONTINUE END INPUT PRINT
RANDOMIZE PRECISION DEB_MODE

10 a = 7   REM this is a label
20 b = 9   REM another label
30 c = 3   REM yet another label
40 d = 1   REM wow! so many labels!

"Mary had a little lamb"  REM this is a string literal
a = 1.2345   REM that's a variable and a number literal

REM these are the built-in functions.
ABS SGN CINT FIX SQR POW EXP LOG RND
